version: '2'

networks:
  xl_app:

services:
  xlpay-admin:
    container_name: xlpay-admin
    image: xlpay-admin
    networks:
      - xl_app
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 8081:8080
    command: java -Xms512m -Xmx1024m -jar /app.jar --spring.profiles.active=prod --spring.datasource.password=$MYSQL_PASSWORD
